export DEFAULT_USER="$USER"
if [[ "$(uname -s)" == "Darwin" ]]; then
	get_music_info () {
	        state=`osascript -e 'tell application "Spotify" to player state as string'`;
	        if [ $state = "playing" ]; then
	                artist=`osascript -e 'tell application "Spotify" to artist of current track as string'`;
	                track=`osascript -e 'tell application "Spotify" to name of current track as string'`;
	                echo -n "$artist - $track";
	        fi
	}
	POWERLEVEL9K_CUSTOM_MUSIC_INFO="get_music_info"
	POWERLEVEL9K_CUSTOM_MUSIC_INFO_BACKGROUND="cyan"
fi

POWERLEVEL9K_HOME_SUB_ICON='\uE12C'

POWERLEVEL9K_STATUS_VERBOSE=false

POWERLEVEL9K_VCS_GIT_ICON=''
POWERLEVEL9K_VCS_STAGED_ICON='\u00b1'
POWERLEVEL9K_VCS_UNTRACKED_ICON='\u25CF'
POWERLEVEL9K_VCS_UNSTAGED_ICON='\u00b1'
POWERLEVEL9K_VCS_INCOMING_CHANGES_ICON='\u2193'
POWERLEVEL9K_VCS_OUTGOING_CHANGES_ICON='\u2191'

POWERLEVEL9K_RAM_BACKGROUND="black"
POWERLEVEL9K_RAM_FOREGROUND="249"
POWERLEVEL9K_RAM_ELEMENTS=(ram_free)
POWERLEVEL9K_RAM_CRITICAL_VISUAL_IDENTIFIER_COLOR="red"
POWERLEVEL9K_RAM_WARNING_VISUAL_IDENTIFIER_COLOR="yellow"
POWERLEVEL9K_RAM_NORMAL_VISUAL_IDENTIFIER_COLOR="green"
POWERLEVEL9K_LOAD_DEFAULT_BACKGROUND="black"
POWERLEVEL9K_LOAD_DEFAULT_FOREGROUND="249"
POWERLEVEL9K_LOAD_CRITICAL_BACKGROUND="black"
POWERLEVEL9K_LOAD_CRITICAL_FOREGROUND="249"
POWERLEVEL9K_LOAD_WARNING_BACKGROUND="black"
POWERLEVEL9K_LOAD_WARNING_FOREGROUND="249"
POWERLEVEL9K_LOAD_NORMAL_BACKGROUND="black"
POWERLEVEL9K_LOAD_NORMAL_FOREGROUND="249"
POWERLEVEL9K_LOAD_CRITICAL_VISUAL_IDENTIFIER_COLOR="red"
POWERLEVEL9K_LOAD_WARNING_VISUAL_IDENTIFIER_COLOR="yellow"
POWERLEVEL9K_LOAD_NORMAL_VISUAL_IDENTIFIER_COLOR="green"

POWERLEVEL9K_SHORTEN_DIR_LENGTH=3
POWERLEVEL9K_SHORTEN_STRATEGY=truncate_from_right
POWERLEVEL9K_SHORTEN_DELIMITER=..

POWERLEVEL9K_MODE='awesome-patched'

POWERLEVEL9K_PROMPT_ON_NEWLINE=true

POWERLEVEL9K_RBENV_FOREGROUND="black"

POWERLEVEL9K_NVM_FOREGROUND="black"

POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX="\n"
POWERLEVEL9K_MULTILINE_SECOND_PROMPT_PREFIX="%K{white}%F{black} `date +%T` \UE12E %f%k%F{white}%f "

POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(os_icon dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status nvm rbenv virtualenv custom_music_info ram load_joined)
